routes/admin.php
<?php

use App\Http\Controllers\admin\HomeController;
use App\Http\Controllers\admin\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('dashboard');
Route::resource('user', UserController::class);
//Route::get('/admin', function () { return "view('admin.dashboard')";}

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name', 'family', 'mobile', 'address', 'role', 'email', 'email_verified_at', 'password', 'instagram', 'telegram', 'facebook', 'linkedin', 'remember_token',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
        'social' => 'array'
    ];

    public function file(): MorphOne
    {
        return $this->morphOne(File::class,'fileable');
    }

    public function jobs(): HasMany
    {
        return $this->hasMany(Job::class , 'user_id' , 'id');
    }

    public function blogs(): HasMany
    {
        return $this->hasMany(Blog::class, 'user_id' , 'id');
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class,'user_id','id');
    }

    public function skills(): HasMany
    {
        return $this->hasMany(Skill::class,'user_id','id');
    }

    public function studies(): HasMany
    {
        return $this->hasMany(Study::class , 'user_id','id');
    }

}

app/Http/Controllers/admin/UserController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Http\Services\User\UserService;
use App\Models\User;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;

class UserController extends Controller
{

    public function __construct(private UserService $userService)
    {

    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $user = User::first();
        if ($user)
            return redirect(route('admin.user.show',$user->id));
        else
            return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(UserRequest $request)
    {
        $user = $this->userService->store($request->validated());
        return redirect(route('admin.dashboard'));
    }

    /**
     * Display the specified resource.
     */
    public function show(User $user)
    {
        return view('admin.users.create',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UserRequest $request, User $user)
    {
        $this->userService->update($user,$request->validated());
        return redirect(route('admin.dashboard'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $user)
    {
        $this->userService->destroy($user);
        return redirect(view('admin.dashboard'));
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="container mt-5">
        <form method="post" action="{{isset($user) ? route('admin.user.update',$user->id) : route('admin.user.store') }}">
            @csrf
           @if(isset($user)) @method('PATCH') @endif
            <!-- row -->
            <div class="row tm-content-row">
                <div class="tm-block-col tm-col-avatar">
                    <div class="tm-bg-primary-dark tm-block tm-block-avatar">
                        <h2 class="tm-block-title" style="text-align: right">انتخاب تصویر</h2>
                        <div class="tm-avatar-container">
                            <img
                                src="{{URL::asset('admin_assets/img/avatar.png')}}"
                                alt="Avatar"
                                class="tm-avatar img-fluid mb-4"
                            />
                            <a href="#" class="tm-avatar-delete-link">
                                <i class="far fa-trash-alt tm-product-delete-icon"></i>
                            </a>
                        </div>
                        <x-forms.input  name="image" type="file"/>
                    </div>
                </div>
                <div class="tm-block-col tm-col-account-settings">
                    <div class="tm-bg-primary-dark tm-block tm-block-settings">
                        <h2 class="tm-block-title mb-5" style="text-align: center">ثبت اطلاعات کاربر</h2>
                        <div class="tm-signup-form row">

                            <x-forms.input style="text-align:right" class="col-lg-6" name="name" id="name" type="text"
                                           label="نام" value="{{isset($user) ? $user->name : ''}}"/>
                            <x-forms.input style="text-align:right" class="col-lg-6" name="family" id="family"
                                           type="text" label="نام خانوادگی" value="{{isset($user) ? $user->family : ''}}"/>
                            <x-forms.input style="text-align:right" class="col-lg-6" name="mobile" id="mobile"
                                           type="text" label="تلفن همراه" value="{{isset($user) ? $user->mobile : ''}}"/>
                            <x-forms.input style="text-align:right" class="col-lg-6" name="email" id="email"
                                           type="email" label="پست الکترونیک" value="{{isset($user) ? $user->email : ''}}"/>
                            <x-forms.input style="text-align:right" class="col-lg-6" name="password" id="password"
                                           type="password" label="کلمه عبور" />
                            <x-forms.input style="text-align:right" class="col-lg-6" name="confirmPassword"
                                           id="confirmPassword" type="password" label="تکرار کلمه عبور" />

                            <x-forms.input style="text-align:right" class="col-12" name="address" id="address"
                                           type="text" label="آدرس" value="{{isset($user) ? $user->address : ''}}"/>
                            <x-forms.input style="text-align:left" class="col-12" name="facebook" id="facebook"
                                           type="text" label="Facebook" value="{{isset($user) ? $user->facebook : ''}}"/>
                            <x-forms.input style="text-align:left" class="col-12" name="telegram" id="telegram"
                                           type="text" label="Telegram" value="{{isset($user) ? $user->telegram : ''}}"/>
                            <x-forms.input style="text-align:left" class="col-12" name="instagram" id="instagram"
                                           type="text" label="Instagram" value="{{isset($user) ? $user->instagram : ''}}"/>
                            <x-forms.input style="text-align:left" class="col-12" name="linkedin" id="linkedin"
                                           type="text" label="Linkedin" value="{{isset($user) ? $user->linkedin : ''}}"/>

                            <div class="col-12">
                                <x-forms.button button-style="success" title="{{isset($user) ? 'بروزرسانی پروفایل' : 'ثبت کاربر'}}" />
                            </div>
                        </form>
                        @isset($user)
                            <div class="col-12 mt-3">
                                <x-forms.button button-style="danger" title="حذف حساب کاربری"/>
                            </div>
                        @endisset
                        </div>
                    </div>
                </div>
            </div>
    </div>
@endsection